# To these settings you can provide the following values:
# ${chance} - Chance to add heart
heartItem:
  enabled: true
  name: "&c&lExtra Heart"
  material: "RED_DYE" # Material Name, get one from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html !!! CASE SENSITIVE !!!
  lore:
    - "&6Gives an extra heart!"
    - "&7&oYou have ${chance}% to get an additional heart added."
  loseChance: 50 # Chance of losing heart at failure.

banOn0Hearts: true # If true, player will be ip-banned if they have 0 hearts.
broadcastBanFrom0Hearts: true # If true, there will be message visible to everyone that some player got banned.

# INSERT YOUR DATA!
# TEMPLATE:
# loot:
#   enabled: true # If false, loot will not be generated in structures chests.
#   worlds:
#     your_world_name:
#       chanceForHeartToGenerate: 50 # number between 0 and 100
#       heartAddChance: 50 # number between 0 and 100
#     your_second_world_name:
#       chanceForHeartToGenerate: 50 # number between 0 and 100
#       heartAddChance: 50 # number between 0 and 100
#     your_third_world_name:
#       chanceForHeartToGenerate: 50 # number between 0 and 100
#       heartAddChance: 50 # number between 0 and 100


loot:
  enabled: true # If false, loot will not be generated in structures chests.
  worlds:
    world:
      chanceForHeartToGenerate: 100
      heartAddChance: 50
    world_nether:
      chanceForHeartToGenerate: 100
      heartAddChance: 75
    world_the_end:
      chanceForHeartToGenerate: 100
      heartAddChance: 100

messages:
  heartReceived: "&a&lYou've received an extra heart!"
  heartGained: "&a&lYou've gained a heart!"
  heartFailure: "&4&lYou didn't get an extra heart."
  heartLost: "&4&lYou've lost an heart."
  noMoreHeartsBan: "&c&lYou've lost all your lives."
  bannedNoMoreHeartsBroadcast: "&c&l${player} &4&lhas lost all his lives."
  itemDisabled: "&c&lThis item is disabled."
  configReloaded: "&aConfig reloaded."